sudo: required

matrix:
    include:
        - os: linux
          dist: bionic
#        - os: osx
#          osx_image: xcode7.3
#          language: generic
#    allow_failures:
#        - os: osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./dependencies_osx.sh ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./dependencies_ubuntu.sh ; fi

script:
    - cd core/ydk
    - mkdir -p build && cd build && cmake .. && sudo make install test && sudo make package

#    - cd ../../../ietf
#    - mkdir -p build && cd build && cmake -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ .. && sudo make install

#    - cd ../../openconfig
#    - mkdir -p build && cd build && cmake -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ .. && sudo make install

#    - cd ../../cisco-nx-os
#    - mkdir -p build && cd build && cmake -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ .. && sudo make install

before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name ygorelik
    - git config --local user.email ygorelik@cisco.com

deploy:
    provider: releases
    api_key: 96d470c778ca56972a549e22dc84d3bef7415aa5
    file: libydk_0.8.1-1_amd64.deb
    overwrite: true
    skip_cleanup: true
    draft: true
